### PR TITLE
Fix HTMLCollection bug

### PR DESCRIPTION
**Pull request by ZRktty**

### CODE REVIEW

**Comment by rkusa** [comment]
Looks good, thanks! Would you mind removing the `add ignore for jetbrains IDE` commit?

**Comment by ZRdesign** [comment]
sure!

**Comment by rkusa** [comment]
Thanks! 👍

**Comment by rkusa** [comment]
Sure! Published as `1.2.0`

**Comment by rkusa** [comment]
As a headsup, there will be a `2.0.0` soon on NPM. This version will not come from this repository but from one maintained by Github. I'll still merge fixes/improvements into the `1.x` branch, but expect the Github version to be an improvement anyway.

**Pull request merged**
